// frontend/src/pages/TeacherKnowledgeHubPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { listTeacherCourses, type TeacherCourseItem } from '../services/course'
import { useAuth } from '../store/auth'

// TeacherKnowledgeHubPage 教师侧「课程知识库」入口：列出课程并跳转到单课资源列表。
export function TeacherKnowledgeHubPage() {
  const { token } = useAuth()
  const navigate = useNavigate()
  const accessToken = token ?? ''
  const [courses, setCourses] = useState<TeacherCourseItem[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    let cancelled = false
    async function run() {
      setLoading(true)
      setError('')
      try {
        const data = await listTeacherCourses(accessToken, 1, 50, '', '', 'updated_at', 'desc')
        if (!cancelled) setCourses(data.items)
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : '加载课程失败')
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    void run()
    return () => {
      cancelled = true
    }
  }, [accessToken])

  return (
    <div className="course-workspace">
      <header className="card workspace-header">
        <h2>课程知识库管理</h2>
        <p className="subtle">选择课程后管理可解析文档的分块与向量嵌入；也可从「课程列表」直接进入某一门课的知识库。</p>
      </header>
      {error && <div className="alert error">{error}</div>}
      <section className="card stack">
        {loading && <p className="subtle">加载中…</p>}
        {!loading && courses.length === 0 && <p className="subtle">暂无课程，请先在课程列表中创建。</p>}
        <div className="course-list">
          {courses.map((c) => (
            <article key={c.id} className="course-item">
              <div>
                <h4>{c.title}</h4>
                <p className="subtle">{c.description || '暂无描述'}</p>
              </div>
              <div className="action-row">
                <button className="primary" onClick={() => navigate(`/teacher/knowledge/${c.id}`)}>
                  知识库管理
                </button>
              </div>
            </article>
          ))}
        </div>
      </section>
    </div>
  )
}

// frontend/src/pages/teacher/TeacherKnowledgeHubPage.vue
<template>
  <div class="course-workspace">
    <header class="card workspace-header">
      <h2>课程知识库管理</h2>
      <p class="subtle">选择课程后进入资源分块与嵌入管理</p>
    </header>

    <div v-if="error" class="alert error">{{ error }}</div>
    <section class="card stack">
      <div class="course-list">
        <article v-for="course in courses" :key="course.id" class="course-item">
          <div>
            <h4>{{ course.title }}</h4>
            <p class="subtle">{{ course.description || '暂无描述' }}</p>
            <p class="mono">状态：{{ course.status }}</p>
          </div>
          <div class="action-row">
            <button class="primary" @click="$router.push(`/teacher/knowledge/${course.id}`)">进入知识库</button>
          </div>
        </article>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { listTeacherCourses, type TeacherCourseItem } from '@/services/course'
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore()
const courses = ref<TeacherCourseItem[]>([])
const error = ref('')

async function loadCourses() {
  // 加载教师课程列表，用于进入对应课程的知识库管理页。
  try {
    const data = await listTeacherCourses(auth.token ?? '', 1, 100, '', '', 'updated_at', 'desc')
    courses.value = data.items || []
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载课程失败'
  }
}

onMounted(() => void loadCourses())
</script>

<style scoped>
.workspace-header {
  padding-bottom: 16px;
}

.course-item {
  align-items: center;
}

.course-item h4 {
  margin-bottom: 4px;
  font-size: 16px;
}

.course-item .action-row {
  align-items: center;
}
</style>
