// frontend/src/pages/teacher/TeacherKnowledgeResourcesPage.vue
<template>
  <div class="course-workspace">
    <header class="card workspace-header">
      <h2>知识库资源</h2>
      <p class="subtle">课程 ID：{{ courseId }} · 仅列出支持解析与分块的文档类型</p>
      <div class="action-row">
        <button @click="$router.push('/teacher/courses')">返回课程列表</button>
      </div>
    </header>

    <div v-if="error" class="alert error">{{ error }}</div>
    <section v-if="loading" class="card stack">
      <p class="subtle">加载中...</p>
    </section>
    <section class="card stack">
      <div v-if="!loading && items.length === 0" class="subtle">暂无符合条件的资源，请先在课程内容中上传文档资源</div>
      <div v-else class="resource-list">
        <article v-for="item in items" :key="item.id" class="course-item">
          <div>
            <h4>{{ item.title }}</h4>
            <p class="subtle">
              {{ item.chapter_title }} / {{ item.section_title || '未分节' }} · {{ item.resource_type.toUpperCase() }}
            </p>
            <span :class="['status-pill', getStatus(item)]">{{ getStatusLabel(item) }}</span>
            <p class="mono">
              分块：{{ item.chunk_count }} · 已嵌入：{{ item.embedded_count }} · 字符：{{ item.total_chunk_chars }}
            </p>
          </div>
          <div class="action-row">
            <button class="primary" @click="$router.push(`/teacher/knowledge/${courseId}/chunk/${item.id}`)">
              分块管理
            </button>
          </div>
        </article>
      </div>
      <div v-if="total > 0" class="list-toolbar">
        <span class="subtle">共 {{ total }} 条记录，第 {{ page }} / {{ totalPages }} 页</span>
        <div class="action-row">
          <button :disabled="loading || page <= 1" @click="load(page - 1)">上一页</button>
          <button :disabled="loading || page >= totalPages" @click="load(page + 1)">下一页</button>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { listKnowledgeResources, type KnowledgeResourceRow } from '@/services/knowledge'
import { useAuthStore } from '@/stores/auth'

const route = useRoute()
const auth = useAuthStore()
const courseId = String(route.params.courseId || '')

const items = ref<KnowledgeResourceRow[]>([])
const loading = ref(false)
const error = ref('')
const page = ref(1)
const pageSize = 10
const total = ref(0)
const totalPages = ref(1)

function toNum(value: number | string | undefined) {
  if (value === undefined) return 0
  return typeof value === 'number' ? value : Number(value)
}

function getStatus(item: KnowledgeResourceRow) {
  if (toNum(item.embedded_count) > 0) return 'embedded'
  if (toNum(item.chunk_count) > 0) return 'chunked'
  return 'none'
}

function getStatusLabel(item: KnowledgeResourceRow) {
  const s = getStatus(item)
  if (s === 'embedded') return '已嵌入'
  if (s === 'chunked') return '已分块'
  return '未分块'
}

// 支持分页加载知识库资源，便于大课程下的资源管理。
async function load(targetPage = 1) {
  if (!courseId) return
  loading.value = true
  error.value = ''
  // 按课程维度加载已上传的知识资源与分块/嵌入统计信息。
  try {
    const data = await listKnowledgeResources(auth.token ?? '', courseId, targetPage, pageSize)
    items.value = data.items || []
    total.value = toNum(data.total)
    page.value = targetPage
    totalPages.value = Math.max(1, Math.ceil(total.value / pageSize))
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载知识库资源失败'
  } finally {
    loading.value = false
  }
}

onMounted(() => void load())
</script>

<style scoped>
.course-item {
  align-items: center;
  cursor: pointer;
  transition: border-color 0.2s ease, box-shadow 0.2s ease;
}

.course-item:hover {
  border-color: #93c5fd;
  box-shadow: 0 4px 14px rgba(37, 99, 235, 0.1);
}

.resource-list {
  display: grid;
  gap: 10px;
}

.course-item h4 {
  font-size: 16px;
  margin-bottom: 4px;
}

.course-item .mono {
  margin-top: 6px;
}

.status-pill {
  display: inline-block;
  margin-top: 4px;
  margin-bottom: 4px;
  padding: 2px 8px;
  border-radius: 999px;
  font-size: 12px;
  border: 1px solid transparent;
}
.status-pill.none {
  background: #f1f5f9;
  color: #475569;
  border-color: #cbd5e1;
}
.status-pill.chunked {
  background: #eff6ff;
  color: #1d4ed8;
  border-color: #93c5fd;
}
.status-pill.embedded {
  background: #ecfdf5;
  color: #166534;
  border-color: #86efac;
}

.list-toolbar {
  margin-top: 6px;
  padding-top: 10px;
  border-top: 1px solid #e2e8f0;
}
</style>

// frontend-opencode/src/pages/teacher/TeacherKnowledgeResourcesPage.tsx
/**
 * 教师知识库资源列表页面
 * 显示课程下可解析资源的分页列表，提供分块与嵌入入口
 */
import { useEffect, useState, useCallback } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuthStore } from '@/stores/authStore'
import { getKnowledgeResources } from '@/services/knowledge'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'

/**
 * 知识库资源列表项（扩展 Resource 类型，包含分块统计）
 */
interface KnowledgeResourceItem {
  id: string
  chapter_id: string
  section_id: string
  chapter_title: string
  section_title: string
  title: string
  resource_type: string
  total_chunk_chars: number
  chunk_count: number
  embedded_count: number
}

/**
 * 资源状态类型
 */
type ResourceStatus = 'none' | 'chunked' | 'embedded'

/**
 * 根据分块和嵌入数量判断资源状态
 */
function getResourceStatus(chunkCount: number, embeddedCount: number): ResourceStatus {
  if (embeddedCount > 0) {
    return 'embedded'
  }
  if (chunkCount > 0) {
    return 'chunked'
  }
  return 'none'
}

/**
 * 获取状态标签配置
 */
function getStatusBadge(status: ResourceStatus) {
  switch (status) {
    case 'embedded':
      return { variant: 'success' as const, label: '已嵌入' }
    case 'chunked':
      return { variant: 'info' as const, label: '已分块' }
    default:
      return { variant: 'secondary' as const, label: '未分块' }
  }
}

/**
 * 格式化数字显示
 */
function formatNumber(value: number | string | undefined): number {
  if (value === undefined || value === null) return 0
  return typeof value === 'number' ? value : Number(value)
}

export function TeacherKnowledgeResourcesPage() {
  const { courseId = '' } = useParams<{ courseId: string }>()
  const navigate = useNavigate()
  const { token } = useAuthStore()

  const [resources, setResources] = useState<KnowledgeResourceItem[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const [page, setPage] = useState(1)
  const [pageSize] = useState(10)
  const [total, setTotal] = useState(0)

  /**
   * 加载知识库资源列表
   */
  const loadResources = useCallback(async (targetPage: number = 1) => {
    if (!courseId || !token) return

    setLoading(true)
    setError(null)

    try {
      const data = await getKnowledgeResources(Number(courseId), {
        page: targetPage,
        page_size: pageSize,
      })
      setResources(data.items as unknown as KnowledgeResourceItem[])
      setTotal(Number(data.total))
      setPage(targetPage)
    } catch (err) {
      setError(err instanceof Error ? err.message : '加载资源列表失败')
    } finally {
      setLoading(false)
    }
  }, [courseId, token])

  useEffect(() => {
    void loadResources(1)
  }, [loadResources])

  const totalPages = Math.max(1, Math.ceil(total / pageSize))

  /**
   * 跳转到分块管理页面
   */
  function handleResourceClick(resource: KnowledgeResourceItem) {
    navigate(`/teacher/knowledge/${courseId}/chunk/${resource.id}`)
  }

  /**
   * 返回课程列表
   */
  function handleGoBack() {
    navigate('/teacher/courses')
  }

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-4 mb-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleGoBack}
          >
            返回课程列表
          </Button>
        </div>
        <h1 className="text-3xl font-bold text-foreground">知识库资源</h1>
        <p className="text-muted-foreground mt-2">
          课程 ID：{courseId} · 仅列出支持解析与分块的文档类型
        </p>
      </div>

      {error && (
        <div className="p-4 rounded-lg bg-destructive/10 border border-destructive/20">
          <p className="text-sm text-destructive">{error}</p>
        </div>
      )}

      {loading && (
        <Card>
          <CardContent className="py-12">
            <div className="text-center">
              <p className="text-muted-foreground">加载中...</p>
            </div>
          </CardContent>
        </Card>
      )}

      {!loading && resources.length === 0 && (
        <Card>
          <CardContent className="py-12">
            <div className="text-center">
              <p className="text-muted-foreground mb-4">
                暂无符合条件的资源
              </p>
              <p className="text-sm text-muted-foreground">
                请先在课程内容管理中上传文档资源
              </p>
            </div>
          </CardContent>
        </Card>
      )}

      {!loading && resources.length > 0 && (
        <>
          <div className="grid gap-4">
            {resources.map((resource) => {
              const status = getResourceStatus(
                formatNumber(resource.chunk_count),
                formatNumber(resource.embedded_count)
              )
              const statusBadge = getStatusBadge(status)

              return (
                <Card
                  key={resource.id}
                  className="cursor-pointer hover:border-primary/50 transition-colors"
                  onClick={() => handleResourceClick(resource)}
                >
                  <CardHeader>
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <CardTitle className="line-clamp-2">
                          {resource.title}
                        </CardTitle>
                        <CardDescription className="mt-1">
                          {resource.chapter_title}
                          {resource.section_title ? ` · ${resource.section_title}` : ''} · {resource.resource_type.toUpperCase()}
                        </CardDescription>
                      </div>
                      <Badge variant={statusBadge.variant}>
                        {statusBadge.label}
                      </Badge>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="flex flex-wrap gap-4 text-sm text-muted-foreground">
                      <div className="flex items-center gap-1">
                        <span>分块数：</span>
                        <span className="font-medium text-foreground">
                          {formatNumber(resource.chunk_count)}
                        </span>
                      </div>
                      <div className="flex items-center gap-1">
                        <span>已嵌入：</span>
                        <span className="font-medium text-foreground">
                          {formatNumber(resource.embedded_count)}
                        </span>
                      </div>
                      <div className="flex items-center gap-1">
                        <span>字符数：</span>
                        <span className="font-medium text-foreground">
                          {formatNumber(resource.total_chunk_chars).toLocaleString()}
                        </span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )
            })}
          </div>

          {total > 0 && (
            <Card>
              <CardContent className="py-4">
                <div className="flex items-center justify-between">
                  <div className="text-sm text-muted-foreground">
                    共 {total} 条记录，第 {page} / {totalPages} 页
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      disabled={page <= 1 || loading}
                      onClick={() => void loadResources(page - 1)}
                    >
                      上一页
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      disabled={page >= totalPages || loading}
                      onClick={() => void loadResources(page + 1)}
                    >
                      下一页
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  )
}
