// frontend/src/pages/teacher/TeacherQuestionBankHubPage.vue
<template>
  <div class="course-workspace">
    <header class="card workspace-header">
      <h2>课程题库管理</h2>
      <p class="subtle">选择课程后进入题库，支持手工编辑与上传文本 AI 解析导题。</p>
    </header>

    <div v-if="error" class="alert error">{{ error }}</div>
    <section class="card stack">
      <div v-if="loading" class="subtle">加载中...</div>
      <div v-else-if="courses.length === 0" class="subtle">暂无课程，请先创建课程</div>
      <div v-else class="course-list">
        <article v-for="course in courses" :key="course.id" class="course-item">
          <div>
            <h4>{{ course.title }}</h4>
            <p class="subtle">{{ course.description || '暂无描述' }}</p>
          </div>
          <div class="action-row">
            <button class="primary" @click="$router.push(`/teacher/question-bank/${course.id}/list`)">进入题库</button>
          </div>
        </article>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { listTeacherCourses, type TeacherCourseItem } from '@/services/course'
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore()
const courses = ref<TeacherCourseItem[]>([])
const loading = ref(false)
const error = ref('')

// 课程题库入口只负责课程选择，不承载题目编辑逻辑。
async function loadCourses() {
  loading.value = true
  error.value = ''
  try {
    const out = await listTeacherCourses(auth.token ?? '', 1, 100, '', '', 'updated_at', 'desc')
    courses.value = out.items || []
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载课程失败'
  } finally {
    loading.value = false
  }
}

onMounted(() => void loadCourses())
</script>

// frontend-opencode/src/pages/teacher/TeacherQuestionBankHubPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { getCourses } from '@/services/course'
import { useAuthStore } from '@/stores/authStore'
import type { Course } from '@/types'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { FileText, ArrowRight } from 'lucide-react'

// 题库入口页：按课程维度进入题库管理。
export function TeacherQuestionBankHubPage() {
  const navigate = useNavigate()
  const { token } = useAuthStore()
  const accessToken = token ?? ''
  const [courses, setCourses] = useState<Course[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false
    async function loadCourses() {
      setLoading(true)
      setError(null)
      try {
        const data = await getCourses(accessToken, {
          page: 1,
          page_size: 100,
          sort_by: 'updated_at',
          sort_order: 'desc',
        })
        if (!cancelled) setCourses(data.items)
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : '加载课程失败')
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    void loadCourses()
    return () => {
      cancelled = true
    }
  }, [accessToken])

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-foreground">课程题库</h1>
        <p className="text-muted-foreground mt-2">选择课程后进入题库管理，支持手工编辑和上传文本 AI 导题。</p>
      </div>

      {error && (
        <div className="p-4 rounded-lg bg-destructive/10 border border-destructive/20">
          <p className="text-sm text-destructive">{error}</p>
        </div>
      )}

      {loading ? (
        <Card>
          <CardContent className="py-12 text-center text-muted-foreground">加载中...</CardContent>
        </Card>
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {courses.map((course) => (
            <Card key={course.id} className="group flex flex-col">
              <CardHeader>
                <div className="flex items-start gap-3">
                  <div className="rounded-lg bg-primary/10 p-2.5">
                    <FileText className="h-5 w-5 text-primary" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <CardTitle className="line-clamp-2 text-lg">{course.title}</CardTitle>
                    <CardDescription className="line-clamp-2 mt-1">{course.description || '暂无描述'}</CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="mt-auto border-t pt-4">
                <Button className="w-full" onClick={() => navigate(`/teacher/question-bank/${course.id}/list`)}>
                  进入题库
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
