// frontend/src/pages/teacher/TeacherCourseContentPage.vue
<template>
  <div class="course-workspace">
    <header class="card workspace-header">
      <h2>章节与资源管理</h2>
      <p class="subtle">课程结构：章节 -> 节 -> 资源</p>
      <div class="action-row">
        <button @click="$router.push('/teacher/courses')">返回课程列表</button>
        <button class="primary" @click="openChapterCreate">新增章节</button>
      </div>
    </header>

    <div v-if="error" class="alert error">{{ error }}</div>

    <section class="card stack" v-if="chapters.length === 0 && !loading">
      <p class="subtle">暂无章节</p>
    </section>

    <section class="card stack chapter-card" v-for="chapter in chapters" :key="chapter.id">
      <div class="chapter-title-row">
        <h3>{{ chapter.sort_order }}. {{ chapter.title }}</h3>
        <div class="action-row">
          <button @click="openSectionCreate(chapter.id)">新增节</button>
          <button class="danger" @click="handleDeleteChapter(chapter.id)">删除章节</button>
        </div>
      </div>

      <div v-for="section in sectionsByChapter[chapter.id] || []" :key="section.id" class="section-box">
        <div class="chapter-title-row">
          <strong>{{ section.sort_order }}. {{ section.title }}</strong>
          <div class="action-row">
            <button @click="openUpload(section.id)">上传资源</button>
            <button class="danger" @click="handleDeleteSection(section.id)">删除节</button>
          </div>
        </div>

        <div class="resource-list">
          <article v-for="res in resourcesBySection[section.id] || []" :key="res.id" class="course-item resource-row">
            <div>
              <h4>{{ res.title }}</h4>
              <p class="subtle">
                {{ res.resource_type }} · {{ prettySize(res.size_bytes) }}
              </p>
              <p v-if="res.ai_summary_status === 'running'" class="subtle">摘要生成中…</p>
              <p v-if="res.ai_summary_status === 'failed'" class="alert error" style="margin-top: 6px">
                {{ res.ai_summary_error || '摘要失败' }}
              </p>
            </div>
            <div class="action-row">
              <button @click="openPreview(res.id)">预览</button>
              <button
                v-if="canSummary(res.resource_type)"
                @click="handleSummary(res.id)"
                :disabled="res.ai_summary_status === 'running'"
              >
                AI 摘要
              </button>
              <button class="danger" @click="handleDeleteResource(res.id)">删除</button>
            </div>
          </article>
        </div>
      </div>
    </section>

    <div v-if="chapterModal" class="modal-mask" @click="chapterModal = false">
      <div class="modal-card" @click.stop>
        <h3>新增章节</h3>
        <label>标题 <input v-model="chapterForm.title" /></label>
        <label>排序 <input type="number" min="1" v-model.number="chapterForm.sort_order" /></label>
        <div class="action-row">
          <button @click="chapterModal = false">取消</button>
          <button class="primary" @click="submitChapter">创建</button>
        </div>
      </div>
    </div>

    <div v-if="sectionModal" class="modal-mask" @click="sectionModal = false">
      <div class="modal-card" @click.stop>
        <h3>新增节</h3>
        <label>标题 <input v-model="sectionForm.title" /></label>
        <label>排序 <input type="number" min="1" v-model.number="sectionForm.sort_order" /></label>
        <div class="action-row">
          <button @click="sectionModal = false">取消</button>
          <button class="primary" @click="submitSection">创建</button>
        </div>
      </div>
    </div>

    <div v-if="uploadModal" class="modal-mask" @click="uploadModal = false">
      <div class="modal-card" @click.stop>
        <h3>上传资源</h3>
        <label>文件 <input type="file" @change="onFileChange" /></label>
        <label>标题 <input v-model="uploadForm.title" /></label>
        <label>排序 <input type="number" min="1" v-model.number="uploadForm.sort_order" /></label>
        <div class="action-row">
          <button @click="uploadModal = false">取消</button>
          <button class="primary" :disabled="!uploadFile" @click="submitUpload">上传</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  createChapter,
  createSection,
  listCourseChapters,
  listCourseSections,
  listSectionResources,
  initUpload,
  confirmResource,
  deleteChapter,
  deleteSection,
  deleteResource,
  summarizeResource,
  type ChapterItem,
  type SectionItem,
  type ResourceItem,
} from '@/services/course'
import { useAuthStore } from '@/stores/auth'

const route = useRoute()
const router = useRouter()
const auth = useAuthStore()
const token = computed(() => auth.token ?? '')
const courseId = computed(() => String(route.params.courseId ?? ''))

const chapters = ref<ChapterItem[]>([])
const sectionsByChapter = ref<Record<string, SectionItem[]>>({})
const resourcesBySection = ref<Record<string, ResourceItem[]>>({})
const loading = ref(false)
const error = ref('')

const chapterModal = ref(false)
const sectionModal = ref(false)
const uploadModal = ref(false)
const currentChapterId = ref('')
const currentSectionId = ref('')
const uploadFile = ref<File | null>(null)

const chapterForm = reactive({ title: '', sort_order: 1 })
const sectionForm = reactive({ title: '', sort_order: 1 })
const uploadForm = reactive({ title: '', sort_order: 1 })

const DOC_TYPES = new Set(['pdf', 'txt', 'doc', 'docx', 'ppt'])

function canSummary(type: string) {
  return DOC_TYPES.has(type)
}

function prettySize(v?: number) {
  const bytes = Number(v || 0)
  if (!bytes) return '0 B'
  const mb = bytes / 1024 / 1024
  return `${mb.toFixed(2)} MB`
}

function inferType(fileName: string): ResourceItem['resource_type'] {
  const ext = fileName.toLowerCase().split('.').pop() || ''
  if (ext === 'pdf') return 'pdf'
  if (ext === 'doc') return 'doc'
  if (ext === 'docx') return 'docx'
  if (ext === 'ppt' || ext === 'pptx') return 'ppt'
  if (ext === 'txt' || ext === 'md') return 'txt'
  if (['mp3', 'wav', 'ogg', 'm4a', 'aac', 'flac'].includes(ext)) return 'audio'
  return 'video'
}

function onFileChange(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0] || null
  uploadFile.value = file
  if (file) {
    uploadForm.title = file.name.replace(/\.[^.]+$/, '')
  }
}

async function loadCatalog() {
  if (!courseId.value) return
  loading.value = true
  error.value = ''
  try {
    const ch = await listCourseChapters(token.value, courseId.value)
    chapters.value = ch.items || []
    const secMap: Record<string, SectionItem[]> = {}
    const resMap: Record<string, ResourceItem[]> = {}
    await Promise.all(
      chapters.value.map(async (c) => {
        const sec = await listCourseSections(token.value, courseId.value, c.id)
        secMap[c.id] = sec.items || []
        await Promise.all(
          (sec.items || []).map(async (s) => {
            const rs = await listSectionResources(token.value, s.id)
            resMap[s.id] = rs.items || []
          }),
        )
      }),
    )
    sectionsByChapter.value = secMap
    resourcesBySection.value = resMap
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载失败'
  } finally {
    loading.value = false
  }
}

function openChapterCreate() {
  chapterForm.title = ''
  chapterForm.sort_order = chapters.value.length + 1
  chapterModal.value = true
}

async function submitChapter() {
  await createChapter(token.value, courseId.value, chapterForm)
  chapterModal.value = false
  await loadCatalog()
}

function openSectionCreate(chapterId: string) {
  currentChapterId.value = chapterId
  const n = (sectionsByChapter.value[chapterId] || []).length + 1
  sectionForm.title = ''
  sectionForm.sort_order = n
  sectionModal.value = true
}

async function submitSection() {
  await createSection(token.value, courseId.value, currentChapterId.value, sectionForm)
  sectionModal.value = false
  await loadCatalog()
}

function openUpload(sectionId: string) {
  currentSectionId.value = sectionId
  const n = (resourcesBySection.value[sectionId] || []).length + 1
  uploadForm.title = ''
  uploadForm.sort_order = n
  uploadFile.value = null
  uploadModal.value = true
}

async function submitUpload() {
  if (!uploadFile.value) return
  const file = uploadFile.value
  const resourceType = inferType(file.name)
  const init = await initUpload(token.value, currentSectionId.value, {
    course_id: Number(courseId.value),
    file_name: file.name,
    resource_type: resourceType,
  })
  const putResp = await fetch(init.upload_url, {
    method: 'PUT',
    headers: { 'Content-Type': file.type || 'application/octet-stream' },
    body: file,
  })
  if (!putResp.ok) throw new Error(`上传失败（${putResp.status}）`)
  await confirmResource(token.value, currentSectionId.value, {
    title: uploadForm.title,
    resource_type: resourceType,
    sort_order: uploadForm.sort_order,
    object_key: init.object_key,
    mime_type: file.type || 'application/octet-stream',
    size_bytes: file.size,
  })
  uploadModal.value = false
  await loadCatalog()
}

async function handleSummary(resourceId: string) {
  await summarizeResource(token.value, resourceId)
  await loadCatalog()
}

async function handleDeleteChapter(id: string) {
  if (!window.confirm('确定删除章节及其所有资源吗？')) return
  await deleteChapter(token.value, id)
  await loadCatalog()
}

async function handleDeleteSection(id: string) {
  if (!window.confirm('确定删除该节及其资源吗？')) return
  await deleteSection(token.value, id)
  await loadCatalog()
}

async function handleDeleteResource(id: string) {
  if (!window.confirm('确定删除资源吗？')) return
  await deleteResource(token.value, id)
  await loadCatalog()
}

function openPreview(resourceId: string) {
  router.push(`/teacher/resources/preview?resource_id=${resourceId}`)
}

onMounted(() => {
  void loadCatalog()
})
</script>

<style scoped>
.chapter-title-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}

.chapter-title-row h3 {
  margin: 0;
  font-size: 18px;
}

.chapter-card {
  border: 1px solid #dbe4f0;
}

.section-box {
  margin-top: 10px;
  border: 1px solid #dbe4f0;
  border-radius: 12px;
  padding: 12px 12px 10px;
  background: #f8fbff;
}

.section-box strong {
  font-size: 15px;
  color: #0f172a;
}

.resource-list {
  margin-top: 10px;
  display: grid;
  gap: 8px;
}

.course-item h4 {
  margin: 0 0 4px;
  font-size: 15px;
}

.resource-row {
  align-items: center;
  border: 1px solid #e2e8f0;
  background: #fff;
}

.resource-row .action-row button {
  min-height: 34px;
  padding: 6px 10px;
  font-size: 13px;
}

.course-item .action-row {
  align-items: center;
}
</style>

// frontend/src/pages/TeacherCourseContentPage.tsx
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  confirmResource,
  createChapter,
  deleteChapter,
  deleteResource,
  initUpload,
  listChapterResources,
  listCourseChapters,
  type ChapterItem,
  type ConfirmResourcePayload,
  type ResourceItem,
} from '../services/course'
import { useAuth } from '../store/auth'

type ResourceType = 'ppt' | 'pdf' | 'txt' | 'video' | 'doc' | 'docx' | 'audio'

export function TeacherCourseContentPage() {
  const { token } = useAuth()
  const { courseId = '' } = useParams()
  const navigate = useNavigate()
  const accessToken = token ?? ''

  const [chapters, setChapters] = useState<ChapterItem[]>([])
  const [resourcesByChapter, setResourcesByChapter] = useState<Record<string, ResourceItem[]>>({})
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(false)
  const [showChapterModal, setShowChapterModal] = useState(false)
  const [showResourceModal, setShowResourceModal] = useState(false)
  const [chapterForm, setChapterForm] = useState({ title: '', sort_order: 1 })
  const [uploadChapterId, setUploadChapterID] = useState('')
  const [resourceFile, setResourceFile] = useState<File | null>(null)
  const [resourceForm, setResourceForm] = useState<ConfirmResourcePayload>({
    title: '',
    resource_type: 'pdf',
    sort_order: 1,
    object_key: '',
    mime_type: 'application/pdf',
    size_bytes: 0,
  })

  async function loadCatalog() {
    if (!courseId) return
    const chapterResp = await listCourseChapters(accessToken, courseId)
    setChapters(chapterResp.items)
    const pairs = await Promise.all(
      chapterResp.items.map(async (chapterItem) => {
        const res = await listChapterResources(accessToken, chapterItem.id)
        return [chapterItem.id, res.items] as const
      }),
    )
    setResourcesByChapter(Object.fromEntries(pairs))
  }

  useEffect(() => {
    if (!courseId) return
    void loadCatalog()
  }, [courseId])

  function inferResourceType(fileName: string): ResourceType {
    const ext = fileName.toLowerCase().split('.').pop() ?? ''
    if (ext === 'pdf') return 'pdf'
    if (ext === 'txt' || ext === 'md' || ext === 'markdown') return 'txt'
    if (ext === 'doc') return 'doc'
    if (ext === 'docx') return 'docx'
    if (ext === 'ppt' || ext === 'pptx') return 'ppt'
    if (['mp3', 'wav', 'ogg', 'oga', 'm4a', 'aac', 'flac', 'wma'].includes(ext)) return 'audio'
    if (['mp4', 'mov', 'mkv', 'webm', 'avi'].includes(ext)) return 'video'
    return 'pdf'
  }

  function inferMimeType(file: File): string {
    if (file.type) return file.type
    const ext = file.name.toLowerCase().split('.').pop() ?? ''
    if (ext === 'pdf') return 'application/pdf'
    if (ext === 'txt') return 'text/plain; charset=utf-8'
    if (ext === 'md' || ext === 'markdown') return 'text/markdown; charset=utf-8'
    if (ext === 'ppt') return 'application/vnd.ms-powerpoint'
    if (ext === 'pptx') {
      return 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
    }
    if (ext === 'doc') return 'application/msword'
    if (ext === 'docx') {
      return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    }
    if (ext === 'mp3') return 'audio/mpeg'
    if (ext === 'wav') return 'audio/wav'
    if (ext === 'ogg' || ext === 'oga') return 'audio/ogg'
    if (ext === 'm4a') return 'audio/mp4'
    if (ext === 'aac') return 'audio/aac'
    if (ext === 'flac') return 'audio/flac'
    if (ext === 'wma') return 'audio/x-ms-wma'
    if (['mp4', 'mov', 'mkv', 'webm', 'avi'].includes(ext)) return 'video/mp4'
    return 'application/octet-stream'
  }

  /** 下一可用资源排序号：表 chapter_resources 对 (chapter_id, sort_order) 唯一，不可固定为 1。 */
  function nextResourceSortOrder(chapterId: string): number {
    const list = resourcesByChapter[chapterId] ?? []
    let max = 0
    for (const r of list) {
      if (r.sort_order > max) max = r.sort_order
    }
    return max + 1
  }

  function resourceTagLabel(resourceItem: ResourceItem): string {
    const mime = (resourceItem.mime_type ?? '').toLowerCase()
    const url = (resourceItem.object_url ?? '').toLowerCase()

    // markdown / txt
    if (mime.includes('text/markdown') || url.endsWith('.md') || url.endsWith('.markdown')) return 'md'
    if (mime.startsWith('text/plain')) return 'txt'
    if (resourceItem.resource_type === 'txt') return 'txt'

    // office docs
    if (resourceItem.resource_type === 'pdf') return 'pdf'
    if (resourceItem.resource_type === 'doc') return 'doc'
    if (resourceItem.resource_type === 'docx') return 'docx'
    if (resourceItem.resource_type === 'ppt') {
      if (
        mime.includes('presentationml') ||
        mime.includes('openxmlformats-officedocument.presentationml.presentation') ||
        url.endsWith('.pptx')
      )
        return 'pptx'
      return 'ppt'
    }

    // video / audio: 优先取 mime 的 subtype（video/mp4 -> mp4），否则按扩展名兜底。
    if (resourceItem.resource_type === 'video') {
      const major = mime.split(';')[0]
      if (major.startsWith('video/')) return major.split('/')[1] || 'video'
      if (url.endsWith('.mp4')) return 'mp4'
      return 'video'
    }
    if (resourceItem.resource_type === 'audio') {
      const major = mime.split(';')[0]
      if (major.startsWith('audio/')) return major.split('/')[1] || 'audio'
      if (url.endsWith('.mp3')) return 'mp3'
      if (url.endsWith('.wav')) return 'wav'
      if (url.endsWith('.ogg') || url.endsWith('.oga')) return 'ogg'
      if (url.endsWith('.m4a')) return 'm4a'
      if (url.endsWith('.aac')) return 'aac'
      if (url.endsWith('.flac')) return 'flac'
      if (url.endsWith('.wma')) return 'wma'
      return 'audio'
    }

    return resourceItem.resource_type
  }

  function openPreview(resourceItem: ResourceItem) {
    const previewURL = resourceItem.preview_url || resourceItem.object_url
    const originalURL = resourceItem.object_url || previewURL
    if (!previewURL || !originalURL) {
      setError('该资源缺少访问地址，无法预览')
      return
    }
    const query = new URLSearchParams({
      title: resourceItem.title,
      resource_id: resourceItem.id,
      url: previewURL,
      original_url: originalURL,
      mime_type: resourceItem.mime_type ?? '',
      resource_type: resourceItem.resource_type,
    })
    navigate(`/teacher/resources/preview?${query.toString()}`)
  }

  async function handleCreateChapter(): Promise<boolean> {
    if (!courseId) return false
    setLoading(true)
    setError('')
    setMessage('')
    try {
      await createChapter(accessToken, courseId, chapterForm)
      setChapterForm({ title: '', sort_order: 1 })
      await loadCatalog()
      setMessage('章节创建成功')
      return true
    } catch (err) {
      setError(err instanceof Error ? err.message : '创建章节失败')
      return false
    } finally {
      setLoading(false)
    }
  }

  async function handleUploadResource(): Promise<boolean> {
    if (!courseId || !uploadChapterId || !resourceFile) return false
    setLoading(true)
    setError('')
    setMessage('')
    try {
      const placedOrder = resourceForm.sort_order
      const initData = await initUpload(accessToken, uploadChapterId, {
        course_id: Number(courseId),
        file_name: resourceFile.name,
        resource_type: resourceForm.resource_type,
      })
      const putResp = await fetch(initData.upload_url, {
        method: 'PUT',
        headers: { 'Content-Type': inferMimeType(resourceFile) },
        body: resourceFile,
      })
      if (!putResp.ok) throw new Error(`文件上传失败（${putResp.status}）`)
      await confirmResource(accessToken, uploadChapterId, {
        ...resourceForm,
        object_key: initData.object_key,
        mime_type: inferMimeType(resourceFile),
        size_bytes: resourceFile.size,
      })
      await loadCatalog()
      setResourceFile(null)
      setResourceForm({
        title: '',
        resource_type: 'pdf',
        sort_order: placedOrder + 1,
        object_key: '',
        mime_type: 'application/pdf',
        size_bytes: 0,
      })
      setMessage('资源上传并入库成功')
      return true
    } catch (err) {
      setError(err instanceof Error ? err.message : '上传资源失败')
      return false
    } finally {
      setLoading(false)
    }
  }

  if (!courseId) {
    return (
      <div className="course-workspace">
        <div className="card">
          <h3>未选择课程</h3>
          <p className="subtle">请先从课程列表进入章节与资源管理。</p>
          <button onClick={() => navigate('/teacher/courses')}>返回课程列表</button>
        </div>
      </div>
    )
  }

  return (
    <div className="course-workspace">
      <header className="card workspace-header">
        <h2>章节与资源管理</h2>
        <p className="subtle">当前课程 ID：{courseId}</p>
      </header>
      {message && <div className="alert success">{message}</div>}
      {error && <div className="alert error">{error}</div>}

      <section className="card catalog-panel">
        <div className="list-toolbar">
          <h3>章节目录</h3>
          <button className="primary" onClick={() => setShowChapterModal(true)}>
            + 新增章节
          </button>
        </div>
        {chapters.length === 0 && <p className="subtle">暂无章节</p>}
        {chapters.map((chapterItem) => (
          <section key={chapterItem.id} className="catalog-chapter">
            <div className="catalog-chapter-title">
              <span className="dot" />
              <strong>
                {chapterItem.sort_order}. {chapterItem.title}
              </strong>
              <div className="action-row">
                <button
                  onClick={() => {
                    setUploadChapterID(chapterItem.id)
                    const nextOrder = nextResourceSortOrder(chapterItem.id)
                    setResourceForm((v) => ({ ...v, sort_order: nextOrder }))
                    setShowResourceModal(true)
                  }}
                >
                  + 资源
                </button>
                <button
                  className="danger"
                  onClick={async () => {
                    if (
                      !window.confirm(
                        `确定删除章节「${chapterItem.title}」及其下资源？此操作不可恢复。`,
                      )
                    )
                      return
                    setError('')
                    try {
                      await deleteChapter(accessToken, chapterItem.id)
                      await loadCatalog()
                      setMessage('章节已删除')
                    } catch (err) {
                      setError(err instanceof Error ? err.message : '删除章节失败')
                    }
                  }}
                >
                  删除章节
                </button>
              </div>
            </div>
            <div className="catalog-resource-list">
              {(resourcesByChapter[chapterItem.id] ?? []).map((resourceItem) => (
                <div key={resourceItem.id} className="catalog-resource-row">
                  <span className="resource-tag">{resourceTagLabel(resourceItem)}</span>
                  <button className="catalog-resource-title" onClick={() => openPreview(resourceItem)}>
                    {resourceItem.title}
                  </button>
                  <button
                    className="danger"
                    onClick={async () => {
                      if (!window.confirm(`确定删除资源「${resourceItem.title}」？`)) return
                      setError('')
                      try {
                        await deleteResource(accessToken, resourceItem.id)
                        await loadCatalog()
                        setMessage('资源已删除')
                      } catch (err) {
                        setError(err instanceof Error ? err.message : '删除资源失败')
                      }
                    }}
                  >
                    删除
                  </button>
                </div>
              ))}
              {(resourcesByChapter[chapterItem.id] ?? []).length === 0 && (
                <p className="subtle">该章节暂无资源</p>
              )}
            </div>
          </section>
        ))}
      </section>

      {showChapterModal && (
        <div className="modal-mask" onClick={() => setShowChapterModal(false)}>
          <div className="modal-card" onClick={(e) => e.stopPropagation()}>
            <h3>新增章节</h3>
            <label>
              章节标题
              <input
                value={chapterForm.title}
                onChange={(e) => setChapterForm((v) => ({ ...v, title: e.target.value }))}
              />
            </label>
            <label>
              排序
              <input
                type="number"
                min={1}
                value={chapterForm.sort_order}
                onChange={(e) => setChapterForm((v) => ({ ...v, sort_order: Number(e.target.value) || 1 }))}
              />
            </label>
            <div className="action-row">
              <button onClick={() => setShowChapterModal(false)}>取消</button>
              <button
                className="primary"
                disabled={!chapterForm.title || loading}
                onClick={async () => {
                  const ok = await handleCreateChapter()
                  if (ok) setShowChapterModal(false)
                }}
              >
                确定
              </button>
            </div>
          </div>
        </div>
      )}

      {showResourceModal && (
        <div className="modal-mask" onClick={() => setShowResourceModal(false)}>
          <div className="modal-card" onClick={(e) => e.stopPropagation()}>
            <h3>上传资源</h3>
            <label>
              文件
              <input
                type="file"
                accept=".txt,.pdf,.doc,.docx,.ppt,.pptx,.md,.markdown,.mp4,.mov,.mkv,.webm,.avi,.mp3,.wav,.ogg,.oga,.m4a,.aac,.flac,.wma,video/*,audio/*"
                onChange={(e) => {
                  const file = e.target.files?.[0] ?? null
                  setResourceFile(file)
                  if (!file) return
                  const title = file.name.replace(/\.[^.]+$/, '')
                  const resourceType = inferResourceType(file.name)
                  setResourceForm((v) => ({
                    ...v,
                    title,
                    resource_type: resourceType,
                    mime_type: inferMimeType(file),
                    size_bytes: file.size,
                  }))
                }}
              />
            </label>
            <label>
              资源标题
              <input
                value={resourceForm.title}
                onChange={(e) => setResourceForm((v) => ({ ...v, title: e.target.value }))}
              />
            </label>
            <label>
              排序（章节内唯一，默认已取下一个可用序号）
              <input
                type="number"
                min={1}
                value={resourceForm.sort_order}
                onChange={(e) =>
                  setResourceForm((v) => ({ ...v, sort_order: Number(e.target.value) || 1 }))
                }
              />
            </label>
            <div className="action-row">
              <button onClick={() => setShowResourceModal(false)}>取消</button>
              <button
                className="primary"
                disabled={!uploadChapterId || !resourceFile || !resourceForm.title || loading}
                onClick={async () => {
                  const ok = await handleUploadResource()
                  if (ok) setShowResourceModal(false)
                }}
              >
                上传
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
