// frontend/src/pages/teacher/TeacherKnowledgeChatDetailPage.vue
<template>
  <div class="chat-page">
    <header class="chat-header">
      <div class="action-row">
        <button @click="$router.push('/teacher/knowledge/chats')">返回列表</button>
        <h2>会话 {{ sessionId }}</h2>
      </div>
    </header>

    <div v-if="error" class="alert error">{{ error }}</div>

    <section class="chat-layout">
      <article ref="messageContainerRef" class="card chat-messages">
        <div v-if="messages.length === 0" class="subtle">开始提问吧</div>
        <div v-for="m in messages" :key="String(m.id)" class="message-row" :class="m.role === 'user' ? 'user' : 'assistant'">
          <div class="message-meta">
            <span>{{ m.role === 'user' ? '你' : '助手' }}</span>
            <span>{{ formatTime(m.created_at) }}</span>
            <span v-if="m.isStreaming" class="typing-flag">正在输入...</span>
          </div>
          <div class="message-bubble">
            <template v-if="m.role === 'assistant'">
              <div class="msg-content markdown-body" v-html="renderAssistantContent(m.content)" />
              <span v-if="m.isStreaming" class="cursor">▋</span>
            </template>
            <pre v-else class="msg-content">{{ m.content }}</pre>
          </div>
          <section v-if="m.references_json && m.references_json.length > 0" class="refs">
            <div class="refs-title">引用内容（{{ m.references_json.length }}）</div>
            <article v-for="(r, idx) in m.references_json" :key="`${m.id}-${idx}`" class="ref-card">
              <button class="ref-head" @click="toggleRef(String(m.id), idx)">
                <span class="ref-chevron">{{ isRefExpanded(String(m.id), idx) ? '▾' : '▸' }}</span>
                <span class="ref-text">[{{ r.citation_no || idx + 1 }}] {{ r.resource_title }} #{{ (r.chunk_index || 0) + 1 }}</span>
              </button>
              <div v-if="isRefExpanded(String(m.id), idx)" class="ref-body">
                <p>{{ r.snippet || '（无摘要片段）' }}</p>
                <button v-if="r.full_content" class="link-btn" @click="openRef(r)">查看完整内容</button>
              </div>
            </article>
          </section>
        </div>
      </article>

      <aside class="chat-side">
        <label>
          TopK
          <input v-model.number="topK" type="number" min="1" max="20" />
        </label>
        <label>
          语义阈值
          <input v-model.number="semanticMinScore" type="number" min="0" max="1" step="0.01" />
        </label>
        <label>
          关键词阈值
          <input v-model.number="keywordMinScore" type="number" min="0" max="1" step="0.01" />
        </label>
        <label>
          问答模型
          <select v-model="qaModelId">
            <option value="">默认模型</option>
            <option v-for="m in qaModels" :key="m.id" :value="String(m.id)">
              {{ m.name }} ({{ m.model_id }})
            </option>
          </select>
        </label>
        <button @click="loadMessages">刷新历史</button>
      </aside>
    </section>

    <footer class="chat-input">
      <textarea
        v-model="question"
        placeholder="输入问题（Enter 发送，Shift+Enter 换行）"
        :disabled="asking"
        @keydown="handleKeyDown"
      />
      <button class="primary" :disabled="asking || !question.trim()" @click="handleAsk">
        {{ asking ? '思考中...' : '发送' }}
      </button>
    </footer>

    <div v-if="refViewer" class="modal-mask">
      <div class="modal-panel card stack">
        <h3>{{ refViewer.title }}</h3>
        <pre class="mono ref-content">{{ refViewer.content }}</pre>
        <div class="action-row">
          <button @click="refViewer = null">关闭</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { nextTick, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import MarkdownIt from 'markdown-it'
import DOMPurify from 'dompurify'
import { useAuthStore } from '@/stores/auth'
import { listAIModels, type AIModelItem } from '@/services/aiModels'
import {
  listChatMessages,
  askInSessionStream,
  type ChatMessageItem,
} from '@/services/knowledgeChat'

type MessageRow = ChatMessageItem & { isStreaming?: boolean }

const route = useRoute()
const auth = useAuthStore()
const sessionId = String(route.params.sessionId || '')

const messages = ref<MessageRow[]>([])
const question = ref('')
const asking = ref(false)
const error = ref('')
const qaModels = ref<AIModelItem[]>([])
const qaModelId = ref('')

const topK = ref(8)
const semanticMinScore = ref(0)
const keywordMinScore = ref(0)
const messageContainerRef = ref<HTMLElement | null>(null)
const refViewer = ref<{ title: string; content: string } | null>(null)
const md = new MarkdownIt({ linkify: true, breaks: true, html: false })
const expandedRefKeys = ref<Set<string>>(new Set())

function formatTime(value: string) {
  return value ? new Date(value).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }) : '-'
}

// 将模型输出的 Markdown 转为安全 HTML，避免直接注入不可信内容。
function renderAssistantContent(content: string) {
  const html = md.render(content || '')
  return DOMPurify.sanitize(html)
}

function openRef(reference: {
  citation_no?: number
  resource_title?: string
  snippet?: string
  full_content?: string
}) {
  refViewer.value = {
    title: `[${reference.citation_no || 1}] ${reference.resource_title || '引用内容'}`,
    content: reference.full_content || reference.snippet || '',
  }
}

function makeRefKey(messageId: string, idx: number) {
  return `${messageId}-${idx}`
}

function isRefExpanded(messageId: string, idx: number) {
  return expandedRefKeys.value.has(makeRefKey(messageId, idx))
}

// 引用块按消息+索引独立折叠，避免一次展开影响其他消息。
function toggleRef(messageId: string, idx: number) {
  const key = makeRefKey(messageId, idx)
  const next = new Set(expandedRefKeys.value)
  if (next.has(key)) next.delete(key)
  else next.add(key)
  expandedRefKeys.value = next
}

// 拉取会话历史并归一化引用字段，便于统一渲染。
async function loadMessages() {
  if (!sessionId) return
  error.value = ''
  try {
    const out = await listChatMessages(auth.token ?? '', sessionId, 1, 200)
    messages.value = (out.items || []).map((m) => ({
      ...m,
      references_json: m.references_json || [],
    }))
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载历史失败'
  }
}

// 加载 QA 模型供会话参数选择，默认选中第一项。
async function loadQAModels() {
  try {
    const out = await listAIModels(auth.token ?? '')
    qaModels.value = (out.items || []).filter((m) => m.model_type === 'qa')
    if (!qaModelId.value && qaModels.value.length > 0) {
      qaModelId.value = String(qaModels.value[0].id)
    }
  } catch {
    // 模型加载失败不阻塞问答流程。
  }
}

// 发送提问并消费 SSE，实时拼接 assistant 内容。
async function handleAsk() {
  if (!question.value.trim() || asking.value || !sessionId) return
  asking.value = true
  error.value = ''
  const askText = question.value.trim()
  question.value = ''
  const tmpUserId = `tmp-user-${Date.now()}`
  const tmpAssistantId = `tmp-assistant-${Date.now()}`

  messages.value.push(
    {
      id: tmpUserId,
      session_id: sessionId,
      role: 'user',
      content: askText,
      created_at: new Date().toISOString(),
      references_json: [],
    },
    {
      id: tmpAssistantId,
      session_id: sessionId,
      role: 'assistant',
      content: '',
      created_at: new Date().toISOString(),
      references_json: [],
      isStreaming: true,
    },
  )

  try {
    await askInSessionStream(
      auth.token ?? '',
      sessionId,
      askText,
      topK.value,
      qaModelId.value || undefined,
      semanticMinScore.value,
      keywordMinScore.value,
      {
        onToken: (token) => {
          messages.value = messages.value.map((m) =>
            String(m.id) === tmpAssistantId ? { ...m, content: m.content + token } : m,
          )
        },
        onReferences: (refs) => {
          messages.value = messages.value.map((m) =>
            String(m.id) === tmpAssistantId ? { ...m, references_json: refs } : m,
          )
        },
        onDone: () => {
          messages.value = messages.value.map((m) =>
            String(m.id) === tmpAssistantId ? { ...m, isStreaming: false } : m,
          )
        },
        onError: (message) => {
          error.value = message
        },
      },
    )
    await loadMessages()
  } catch (err) {
    error.value = err instanceof Error ? err.message : '提问失败'
    messages.value = messages.value.filter((m) => String(m.id) !== tmpUserId && String(m.id) !== tmpAssistantId)
  } finally {
    asking.value = false
  }
}

function handleKeyDown(event: KeyboardEvent) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault()
    void handleAsk()
  }
}

watch(
  messages,
  async () => {
    await nextTick()
    if (messageContainerRef.value) {
      messageContainerRef.value.scrollTop = messageContainerRef.value.scrollHeight
    }
  },
  { deep: true },
)

onMounted(async () => {
  await Promise.all([loadQAModels(), loadMessages()])
})
</script>

<style scoped>
.chat-page {
  height: 100%;
  min-height: 0;
  display: flex;
  flex-direction: column;
  gap: 0;
}
.chat-header {
  flex: 0 0 auto;
  border-bottom: 1px solid #dbe4f0;
  background: #fff;
  padding: 10px 16px;
}

.chat-header h2 {
  font-size: 18px;
}
.chat-layout {
  min-height: 0;
  flex: 1 1 auto;
  display: grid;
  grid-template-columns: minmax(0, 1fr) 300px;
  gap: 0;
  overflow: hidden;
}
.chat-messages {
  min-height: 0;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 12px 16px;
  border: none;
  border-radius: 0;
  background: #f8fafc;
}
.message-row {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.message-row.user {
  align-items: flex-end;
}
.message-row.assistant {
  align-items: flex-start;
}
.message-meta {
  display: flex;
  gap: 8px;
  font-size: 12px;
  color: #64748b;
  align-items: center;
}
.typing-flag {
  color: #2563eb;
}
.message-bubble {
  max-width: 82%;
  border-radius: 14px;
  padding: 10px 12px;
  background: #fff;
  border: 1px solid #e5e7eb;
  box-shadow: 0 1px 2px rgba(15, 23, 42, 0.05);
}
.message-row.user .message-bubble {
  background: #eff6ff;
  color: #0f172a;
  border-color: #bfdbfe;
}
.msg-content {
  margin: 0;
  white-space: pre-wrap;
  font-family: inherit;
}
.markdown-body :deep(p) {
  margin: 0 0 10px;
}
.markdown-body :deep(p:last-child) {
  margin-bottom: 0;
}
.markdown-body :deep(ul),
.markdown-body :deep(ol) {
  margin: 0 0 10px;
  padding-left: 20px;
}
.markdown-body :deep(pre) {
  background: #0f172a;
  color: #e2e8f0;
  padding: 10px;
  border-radius: 8px;
  overflow: auto;
}
.markdown-body :deep(code) {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
}
.markdown-body :deep(a) {
  color: #2563eb;
  text-decoration: underline;
}
.markdown-body :deep(table) {
  width: 100%;
  border-collapse: collapse;
}
.markdown-body :deep(th),
.markdown-body :deep(td) {
  border: 1px solid #cbd5e1;
  padding: 6px 8px;
}
.cursor {
  animation: blink 1s steps(1) infinite;
}
.refs {
  max-width: 82%;
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.refs-title {
  font-size: 12px;
  color: #64748b;
  font-weight: 600;
}
.ref-card {
  border: 1px solid #e5e7eb;
  border-radius: 10px;
  overflow: hidden;
  background: #f8fafc;
}
.ref-head {
  width: 100%;
  border: 0;
  background: transparent;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 10px;
  text-align: left;
  cursor: pointer;
}
.ref-head:hover {
  background: #f1f5f9;
}
.ref-chevron {
  color: #64748b;
}
.ref-text {
  font-size: 13px;
  color: #0f172a;
}
.ref-body {
  border-top: 1px solid #dbe4f0;
  padding: 8px 10px;
}
.ref-body p {
  margin: 0 0 6px;
  font-size: 13px;
  color: #334155;
  white-space: pre-wrap;
}
.link-btn {
  border: 0;
  background: transparent;
  color: #2563eb;
  cursor: pointer;
  padding: 0;
}
.chat-side {
  min-height: 0;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 10px;
  border-left: 1px solid #dbe4f0;
  padding: 12px 12px 12px 14px;
  background: #fff;
}

.chat-side > label {
  font-size: 13px;
  color: #334155;
}

.chat-side > button {
  margin-top: 4px;
}
.chat-input {
  flex: 0 0 auto;
  display: flex;
  gap: 12px;
  align-items: flex-end;
  border-top: 1px solid #dbe4f0;
  border-radius: 0;
  padding: 8px 10px;
  background: #fff;
}
.chat-input textarea {
  min-height: 60px;
  max-height: 200px;
  border: none;
  box-shadow: none;
  padding: 8px 6px;
}
.chat-input textarea:focus {
  outline: none;
  box-shadow: none;
}
.modal-mask {
  position: fixed;
  inset: 0;
  background: rgba(15, 23, 42, 0.45);
  display: grid;
  place-items: center;
  z-index: 40;
}
.modal-panel {
  width: min(820px, calc(100vw - 32px));
}
.ref-content {
  max-height: 55vh;
  overflow: auto;
  white-space: pre-wrap;
}
@keyframes blink {
  50% {
    opacity: 0;
  }
}
@media (max-width: 960px) {
  .chat-page {
    height: auto;
    min-height: 100%;
  }
  .chat-layout {
    grid-template-columns: 1fr;
  }

  .chat-side {
    border-left: none;
    border-top: 1px solid #dbe4f0;
  }
}
</style>

// frontend/src/pages/TeacherKnowledgeChatDetailPage.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { listTeacherCourses, type TeacherCourseItem } from '../services/course'
import { listAIModels, type AIModelItem } from '../services/aiModels'
import {
  askInSessionStream,
  createChatSession,
  deleteChatSession,
  listChatMessages,
  listChatSessions,
  updateChatSessionTitle,
  type ChatMessageItem,
  type ChatSessionItem,
} from '../services/knowledgeChat'
import { useAuth } from '../store/auth'

// TeacherKnowledgeChatDetailPage 展示单会话历史并支持继续提问。
export function TeacherKnowledgeChatDetailPage() {
  const { token } = useAuth()
  const navigate = useNavigate()
  const { sessionId = '' } = useParams()
  const accessToken = token ?? ''

  const [messages, setMessages] = useState<ChatMessageItem[]>([])
  const [sessions, setSessions] = useState<ChatSessionItem[]>([])
  const [courses, setCourses] = useState<TeacherCourseItem[]>([])
  const [qaModels, setQaModels] = useState<AIModelItem[]>([])
  const [qaModelId, setQaModelId] = useState('')
  const [courseId, setCourseId] = useState('')
  const [question, setQuestion] = useState('')
  const [topK, setTopK] = useState(8)
  const [semanticMinScore, setSemanticMinScore] = useState(0)
  const [keywordMinScore, setKeywordMinScore] = useState(0)
  const [loading, setLoading] = useState(false)
  const [asking, setAsking] = useState(false)
  const [error, setError] = useState('')
  const [streamState, setStreamState] = useState<'idle' | 'streaming' | 'done'>('idle')
  const [editingSessionId, setEditingSessionId] = useState<string | null>(null)
  const [editingTitle, setEditingTitle] = useState('')
  const [refViewer, setRefViewer] = useState<{ title: string; content: string } | null>(null)
  const messageStreamRef = useRef<HTMLDivElement | null>(null)

  async function loadMessages() {
    if (!sessionId) return
    setLoading(true)
    setError('')
    try {
      const data = await listChatMessages(accessToken, sessionId, 1, 200)
      setMessages(data.items)
    } catch (e) {
      setError(e instanceof Error ? e.message : '加载会话历史失败')
    } finally {
      setLoading(false)
    }
  }

  async function loadSessions() {
    try {
      const data = await listChatSessions(accessToken, 1, 100, courseId || undefined)
      setSessions(data.items)
    } catch {
      // ignore
    }
  }

  useEffect(() => {
    let cancelled = false
    async function loadCourses() {
      try {
        const data = await listTeacherCourses(accessToken, 1, 100, '', '', 'updated_at', 'desc')
        if (!cancelled) {
          setCourses(data.items)
          if (data.items.length > 0) setCourseId((v) => v || data.items[0].id)
        }
      } catch {
        // ignore
      }
    }
    void loadCourses()
    return () => {
      cancelled = true
    }
  }, [accessToken])

  useEffect(() => {
    let cancelled = false
    async function loadQAModels() {
      try {
        const data = await listAIModels(accessToken)
        if (cancelled) return
        const models = data.items.filter((m) => m.model_type === 'qa')
        setQaModels(models)
        if (models.length > 0) {
          setQaModelId((v) => v || models[0].id)
        }
      } catch {
        // ignore
      }
    }
    void loadQAModels()
    return () => {
      cancelled = true
    }
  }, [accessToken])

  useEffect(() => {
    void loadMessages()
  }, [sessionId, accessToken])

  useEffect(() => {
    void loadSessions()
  }, [courseId, accessToken, sessionId])

  useEffect(() => {
    const node = messageStreamRef.current
    if (!node) return
    node.scrollTop = node.scrollHeight
  }, [messages, loading])

  async function handleAsk() {
    if (!question.trim()) return
    setAsking(true)
    setError('')
    setStreamState('streaming')
    let done = false
    const askText = question.trim()
    const tmpUserId = `tmp-user-${Date.now()}`
    const tmpAssistantId = `tmp-assistant-${Date.now()}`
    setMessages((prev) => [
      ...prev,
      {
        id: tmpUserId,
        session_id: sessionId,
        role: 'user',
        content: askText,
        created_at: new Date().toISOString(),
      },
      {
        id: tmpAssistantId,
        session_id: sessionId,
        role: 'assistant',
        content: '',
        created_at: new Date().toISOString(),
      },
    ])
    try {
      let finalRefs: Array<{ citation_no?: number; resource_title: string; chunk_index: number; snippet: string; full_content?: string }> = []
      await askInSessionStream(
        accessToken,
        sessionId,
        askText,
        topK,
        qaModelId || undefined,
        semanticMinScore,
        keywordMinScore,
        {
        onToken: (token) => {
          setMessages((prev) =>
            prev.map((m) => (m.id === tmpAssistantId ? { ...m, content: `${m.content}${token}` } : m)),
          )
        },
        onReferences: (refs) => {
          finalRefs = refs.map((r) => ({
            citation_no: r.citation_no,
            resource_title: r.resource_title,
            chunk_index: r.chunk_index,
            snippet: r.snippet,
            full_content: r.full_content,
          }))
          setMessages((prev) =>
            prev.map((m) => (m.id === tmpAssistantId ? { ...m, references_json: finalRefs } : m)),
          )
        },
        onDone: () => {
          done = true
          setStreamState('done')
        },
        onError: (msg) => {
          throw new Error(msg)
        },
      })
      setQuestion('')
      await loadMessages() // 与服务端最终状态对齐
    } catch (e) {
      setMessages((prev) => prev.filter((m) => m.id !== tmpUserId && m.id !== tmpAssistantId))
      setError(e instanceof Error ? e.message : '提问失败')
    } finally {
      setAsking(false)
      if (!done) setStreamState('idle')
    }
  }

  async function handleCreateInCourse() {
    if (!courseId) return
    setError('')
    try {
      const data = await createChatSession(accessToken, courseId, '')
      navigate(`/teacher/knowledge/chats/${data.id}`)
    } catch (e) {
      setError(e instanceof Error ? e.message : '创建会话失败')
    }
  }

  async function handleRenameSession(targetSessionId: string) {
    if (!editingTitle.trim()) {
      setError('标题不能为空')
      return
    }
    try {
      await updateChatSessionTitle(accessToken, targetSessionId, editingTitle.trim())
      setEditingSessionId(null)
      setEditingTitle('')
      await loadSessions()
      if (targetSessionId === sessionId) await loadMessages()
    } catch (e) {
      setError(e instanceof Error ? e.message : '修改标题失败')
    }
  }

  async function handleDeleteSession(targetSessionId: string) {
    if (!window.confirm('确定删除该会话及其所有历史消息？')) return
    try {
      await deleteChatSession(accessToken, targetSessionId)
      await loadSessions()
      if (targetSessionId === sessionId) {
        navigate('/teacher/knowledge/chats')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : '删除会话失败')
    }
  }

  function getCitationNo(ref: NonNullable<ChatMessageItem['references_json']>[number], idx: number) {
    return typeof ref.citation_no === 'number' && ref.citation_no > 0 ? ref.citation_no : idx + 1
  }

  const title = useMemo(() => {
    const currentSession = sessions.find((s) => s.id === sessionId)
    if (currentSession?.title?.trim()) return currentSession.title
    const firstUser = messages.find((m) => m.role === 'user')
    if (!firstUser) return `会话 ${sessionId}`
    return firstUser.content.length > 32 ? `${firstUser.content.slice(0, 32)}...` : firstUser.content
  }, [sessions, messages, sessionId])

  return (
    <div className="chat-page-shell">
      <aside className="chat-left-panel">
        <div className="chat-left-header">
          <h3>对话管理</h3>
          <button onClick={() => navigate('/teacher/knowledge/chats')}>列表页</button>
        </div>
        <label>
          课程（RAG基础）
          <select value={courseId} onChange={(e) => setCourseId(e.target.value)}>
            {courses.map((c) => (
              <option key={c.id} value={c.id}>
                {c.title}
              </option>
            ))}
          </select>
        </label>
        <button className="primary" disabled={!courseId} onClick={() => void handleCreateInCourse()}>
          新建该课程对话
        </button>
        <div className="chat-session-list">
          {sessions.map((s) => (
            <div key={s.id} className={s.id === sessionId ? 'chat-session-item active' : 'chat-session-item'}>
              <button className="chat-session-link" onClick={() => navigate(`/teacher/knowledge/chats/${s.id}`)}>
                <strong>{s.title}</strong>
                <small>{new Date(s.updated_at).toLocaleString()}</small>
              </button>
              <div className="chat-session-actions">
                <button
                  type="button"
                  className="ghost"
                  onClick={() => {
                    setEditingSessionId(s.id)
                    setEditingTitle(s.title)
                  }}
                >
                  重命名
                </button>
                <button type="button" className="danger" onClick={() => void handleDeleteSession(s.id)}>
                  删除
                </button>
              </div>
              {editingSessionId === s.id && (
                <div className="chat-session-edit-row">
                  <input value={editingTitle} onChange={(e) => setEditingTitle(e.target.value)} maxLength={256} />
                  <button type="button" className="primary" onClick={() => void handleRenameSession(s.id)}>
                    保存
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setEditingSessionId(null)
                      setEditingTitle('')
                    }}
                  >
                    取消
                  </button>
                </div>
              )}
            </div>
          ))}
        </div>
      </aside>

      <section className="chat-main-panel">
        <header className="chat-main-header">
          <h2>{title}</h2>
          <div className="action-row">
            <label style={{ width: 140 }}>
              TopK
              <input type="number" min={1} max={20} value={topK} onChange={(e) => setTopK(Number(e.target.value))} />
            </label>
            <label style={{ width: 170 }}>
              语义阈值
              <input
                type="number"
                min={0}
                max={1}
                step={0.01}
                value={semanticMinScore}
                onChange={(e) => setSemanticMinScore(Number(e.target.value))}
              />
            </label>
            <label style={{ width: 170 }}>
              关键词阈值
              <input
                type="number"
                min={0}
                max={1}
                step={0.01}
                value={keywordMinScore}
                onChange={(e) => setKeywordMinScore(Number(e.target.value))}
              />
            </label>
            <label style={{ width: 220 }}>
              问答模型
              <select value={qaModelId} onChange={(e) => setQaModelId(e.target.value)}>
                {qaModels.length === 0 && <option value="">未配置 QA 模型</option>}
                {qaModels.map((m) => (
                  <option key={m.id} value={m.id}>
                    {m.name} ({m.model_id})
                  </option>
                ))}
              </select>
            </label>
            <button onClick={() => void loadMessages()} disabled={loading}>
              刷新
            </button>
          </div>
        </header>
        {error && <div className="alert error">{error}</div>}
        <div className="chat-stream-state subtle">
          <span className={streamState === 'streaming' ? 'dot-streaming' : streamState === 'done' ? 'dot-done' : 'dot-idle'} />
          {streamState === 'streaming' ? '流式输出中...' : streamState === 'done' ? '输出完成' : '等待提问'}
        </div>

        <div ref={messageStreamRef} className="chat-message-stream">
          {loading && <p className="subtle">加载中...</p>}
          {!loading && messages.length === 0 && <p className="subtle">开始提问吧。</p>}
          {messages.map((m) => (
            <article key={m.id} className={m.role === 'user' ? 'chat-bubble user' : 'chat-bubble assistant'}>
              <div className="chat-bubble-meta">
                <strong>{m.role === 'assistant' ? '助手' : m.role === 'user' ? '你' : '系统'}</strong>
                <span className="mono subtle">{new Date(m.created_at).toLocaleString()}</span>
              </div>
              {m.role === 'assistant' ? (
                <div className="chat-markdown-body">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{m.content}</ReactMarkdown>
                </div>
              ) : (
                <pre className="chat-bubble-content">{m.content}</pre>
              )}
              {m.role === 'assistant' && Array.isArray(m.references_json) && m.references_json.length > 0 && (
                <div className="chat-reference-blocks">
                  <div className="chat-reference-blocks-title">引用内容</div>
                  <div className="chat-reference-blocks-list">
                    {m.references_json.map((ref, idx) => (
                      <div key={idx} className="chat-reference-item">
                        <span className="mono subtle">
                          [{getCitationNo(ref, idx)}] {ref.resource_title ?? '未知资源'}
                          {typeof ref.chunk_index === 'number' ? ` #${ref.chunk_index + 1}` : ''}
                        </span>
                        <button
                          type="button"
                          className="ghost"
                          onClick={() =>
                            setRefViewer({
                              title: `[${getCitationNo(ref, idx)}] ${ref.resource_title ?? '未知资源'}`,
                              content: ref.full_content || ref.snippet || '',
                            })
                          }
                        >
                          查看片段
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </article>
          ))}
        </div>

        <div className="chat-input-box">
          <textarea
            rows={2}
            placeholder="给当前课程知识库发送消息（Enter 发送，Shift+Enter 换行）"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault()
                if (!asking && question.trim()) void handleAsk()
              }
            }}
          />
          <button className="primary chat-send-btn" disabled={asking || !question.trim()} onClick={() => void handleAsk()}>
            {asking ? '思考中...' : '发送'}
          </button>
        </div>
      </section>

      {refViewer && (
        <div className="modal-mask" role="presentation">
          <div className="modal-card" role="dialog" aria-modal="true" style={{ maxWidth: 860, width: 'min(860px, 95vw)' }}>
            <div className="modal-card-header">
              <h3>{refViewer.title}</h3>
              <button type="button" className="modal-close-btn" onClick={() => setRefViewer(null)}>
                ×
              </button>
            </div>
            <pre className="chat-ref-viewer">{refViewer.content}</pre>
            <div className="action-row" style={{ justifyContent: 'flex-end' }}>
              <button onClick={() => setRefViewer(null)}>关闭</button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
