// frontend/src/pages/teacher/TeacherAIModelsPage.vue
<template>
  <div class="course-workspace">
    <header class="card workspace-header">
      <h2>AI 模型管理</h2>
      <p class="subtle">管理问答、向量化与重排模型配置</p>
    </header>
    <div v-if="error" class="alert error">{{ error }}</div>
    <div v-if="success" class="alert success">{{ success }}</div>
    <section class="card stack">
      <div class="list-toolbar-actions">
        <input v-model="form.name" placeholder="名称" />
        <select v-model="form.model_type">
          <option value="qa">qa</option>
          <option value="embedding">embedding</option>
          <option value="rerank">rerank</option>
        </select>
        <input v-model="form.api_base_url" placeholder="API Base URL" />
        <input v-model="form.model_id" placeholder="Model ID" />
        <input v-model="form.api_key" type="password" placeholder="API Key（编辑时留空表示沿用）" />
        <button class="primary" @click="handleSubmit">{{ editingId ? '保存修改' : '新增' }}</button>
        <button v-if="editingId" @click="resetForm">取消编辑</button>
        <button :disabled="testing" @click="handleTest">{{ testing ? '测试中...' : '测试连通性' }}</button>
      </div>
      <div class="course-list">
        <article v-for="m in items" :key="m.id" class="course-item">
          <div>
            <h4>{{ m.name }}</h4>
            <p class="mono">{{ m.model_type }} · {{ m.model_id }}</p>
            <p class="subtle">{{ m.api_base_url }}</p>
            <p class="subtle">API Key：{{ m.has_api_key ? '已保存' : '未保存' }}</p>
          </div>
          <div class="action-row">
            <button @click="startEdit(m)">编辑</button>
            <button class="danger" @click="handleDelete(m.id)">删除</button>
          </div>
        </article>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import {
  listAIModels,
  createAIModel,
  updateAIModel,
  deleteAIModel,
  testAIModelConnection,
  type AIModelItem,
} from '@/services/aiModels'
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore()
const items = ref<AIModelItem[]>([])
const error = ref('')
const success = ref('')
const testing = ref(false)
const editingId = ref('')
const form = reactive({
  name: '',
  model_type: 'qa' as 'qa' | 'embedding' | 'rerank',
  api_base_url: '',
  model_id: '',
  api_key: '',
})

async function load() {
  // 加载当前教师下的全部模型配置。
  error.value = ''
  try {
    const data = await listAIModels(auth.token ?? '')
    items.value = data.items || []
  } catch (err) {
    error.value = err instanceof Error ? err.message : '加载模型失败'
  }
}

function resetForm() {
  editingId.value = ''
  form.name = ''
  form.model_type = 'qa'
  form.api_base_url = ''
  form.model_id = ''
  form.api_key = ''
}

function startEdit(item: AIModelItem) {
  editingId.value = item.id
  form.name = item.name
  form.model_type = item.model_type
  form.api_base_url = item.api_base_url
  form.model_id = item.model_id
  form.api_key = ''
}

// 统一处理新增/编辑，避免表单状态重复分叉。
async function handleSubmit() {
  error.value = ''
  success.value = ''
  try {
    if (editingId.value) {
      await updateAIModel(auth.token ?? '', editingId.value, {
        name: form.name,
        api_base_url: form.api_base_url,
        model_id: form.model_id,
        api_key: form.api_key,
      })
      success.value = '模型更新成功'
    } else {
      await createAIModel(auth.token ?? '', form)
      success.value = '模型创建成功'
    }
    resetForm()
    await load()
  } catch (err) {
    error.value = err instanceof Error ? err.message : '提交模型失败'
  }
}

// 连接测试支持新增场景和编辑场景（可复用已有密钥）。
async function handleTest() {
  error.value = ''
  success.value = ''
  testing.value = true
  try {
    const out = await testAIModelConnection(auth.token ?? '', {
      model_type: form.model_type,
      api_base_url: form.api_base_url,
      model_id: form.model_id,
      api_key: form.api_key || undefined,
      existing_model_id: editingId.value || undefined,
    })
    success.value = out.message || (out.ok ? '连通性测试通过' : '连通性测试失败')
  } catch (err) {
    error.value = err instanceof Error ? err.message : '连通性测试失败'
  } finally {
    testing.value = false
  }
}

async function handleDelete(id: string) {
  // 删除指定模型并重新拉取列表。
  error.value = ''
  success.value = ''
  try {
    await deleteAIModel(auth.token ?? '', id)
    success.value = '模型删除成功'
    await load()
  } catch (err) {
    error.value = err instanceof Error ? err.message : '删除模型失败'
  }
}

onMounted(() => void load())
</script>

<style scoped>
.list-toolbar-actions {
  display: grid;
  grid-template-columns: repeat(3, minmax(180px, 1fr));
  gap: 10px;
}

.list-toolbar-actions > input,
.list-toolbar-actions > select,
.list-toolbar-actions > button {
  width: 100%;
}

.course-item {
  align-items: center;
}

.course-item h4 {
  margin-bottom: 4px;
  font-size: 16px;
}

.course-item .action-row {
  align-items: center;
}

.course-item .subtle {
  margin: 2px 0;
}

.success {
  background: #ecfdf5;
  border-color: #86efac;
  color: #166534;
}

@media (max-width: 1200px) {
  .list-toolbar-actions {
    grid-template-columns: repeat(2, minmax(180px, 1fr));
  }
}

@media (max-width: 760px) {
  .list-toolbar-actions {
    grid-template-columns: 1fr;
  }
}
</style>

// frontend/src/pages/TeacherAIModelsPage.tsx
import { useEffect, useState } from 'react'
import {
  createAIModel,
  deleteAIModel,
  listAIModels,
  testAIModelConnection,
  updateAIModel,
  type AIModelItem,
  type AIModelType,
} from '../services/aiModels'
import { useAuth } from '../store/auth'

const MODEL_TYPES: { value: AIModelType; label: string }[] = [
  { value: 'qa', label: '问答' },
  { value: 'embedding', label: '嵌入' },
  { value: 'rerank', label: '重排' },
]

// TeacherAIModelsPage 维护教师的问答 / 嵌入 / 重排模型配置（持久化到服务端）。
export function TeacherAIModelsPage() {
  const { token } = useAuth()
  const accessToken = token ?? ''
  const [items, setItems] = useState<AIModelItem[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [message, setMessage] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [editing, setEditing] = useState<AIModelItem | null>(null)
  const [form, setForm] = useState({
    name: '',
    model_type: 'embedding' as AIModelType,
    api_base_url: '',
    model_id: '',
    api_key: '',
  })
  const [testBusy, setTestBusy] = useState(false)
  const [testHint, setTestHint] = useState<{ ok: boolean; text: string } | null>(null)

  async function load() {
    setLoading(true)
    setError('')
    try {
      const { items: rows } = await listAIModels(accessToken)
      setItems(rows)
    } catch (e) {
      setError(e instanceof Error ? e.message : '加载失败')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load()
  }, [accessToken])

  function openCreate() {
    setEditing(null)
    setTestHint(null)
    setForm({
      name: '',
      model_type: 'embedding',
      api_base_url: 'https://api.openai.com/v1/embeddings',
      model_id: 'text-embedding-3-small',
      api_key: '',
    })
    setShowModal(true)
  }

  function openEdit(m: AIModelItem) {
    setEditing(m)
    setTestHint(null)
    setForm({
      name: m.name,
      model_type: m.model_type,
      api_base_url: m.api_base_url,
      model_id: m.model_id,
      api_key: '',
    })
    setShowModal(true)
  }

  const canTestConnection =
    Boolean(form.api_base_url.trim() && form.model_id.trim()) &&
    (Boolean(form.api_key.trim()) || Boolean(editing?.has_api_key))

  async function runTestConnection() {
    setError('')
    setTestHint(null)
    setTestBusy(true)
    try {
      const data = await testAIModelConnection(accessToken, {
        model_type: form.model_type,
        api_base_url: form.api_base_url.trim(),
        model_id: form.model_id.trim(),
        api_key: form.api_key.trim() || undefined,
        existing_model_id:
          editing && !form.api_key.trim() && editing.has_api_key ? editing.id : undefined,
      })
      setTestHint({ ok: data.ok, text: data.message + (data.http_status ? `（HTTP ${data.http_status}）` : '') })
    } catch (e) {
      setError(e instanceof Error ? e.message : '测试失败')
    } finally {
      setTestBusy(false)
    }
  }

  async function submitModal() {
    setError('')
    setMessage('')
    setLoading(true)
    try {
      if (editing) {
        await updateAIModel(accessToken, editing.id, {
          name: form.name,
          api_base_url: form.api_base_url,
          model_id: form.model_id,
          api_key: form.api_key,
        })
        setMessage('模型已更新（未填写 API Key 则保留原密钥）')
      } else {
        await createAIModel(accessToken, {
          name: form.name,
          model_type: form.model_type,
          api_base_url: form.api_base_url,
          model_id: form.model_id,
          api_key: form.api_key,
        })
        setMessage('模型已添加')
      }
      setShowModal(false)
      await load()
    } catch (e) {
      setError(e instanceof Error ? e.message : '保存失败')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="course-workspace">
      <header className="card workspace-header">
        <div className="action-row" style={{ justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 }}>
          <div>
            <h2>模型管理</h2>
            <p className="subtle">
              配置问答、嵌入、重排模型；保存前可用「测试连接」做最小请求校验（三种类型请求体不同，见表单说明）。
            </p>
          </div>
          <button className="primary" onClick={openCreate}>
            添加模型
          </button>
        </div>
      </header>
      {error && <div className="alert error">{error}</div>}
      {message && <div className="alert success">{message}</div>}

      <section className="card stack">
        {loading && !items.length && <p className="subtle">加载中…</p>}
        <div className="course-list">
          {items.map((m) => (
            <article key={m.id} className="course-item">
              <div>
                <h4>{m.name}</h4>
                <p className="mono subtle">
                  {MODEL_TYPES.find((t) => t.value === m.model_type)?.label ?? m.model_type} · {m.model_id}
                </p>
                <p className="subtle" style={{ fontSize: 13, wordBreak: 'break-all' }}>
                  {m.api_base_url}
                </p>
                <p className="subtle">API Key：{m.has_api_key ? '已配置' : '未配置'}</p>
              </div>
              <div className="action-row">
                <button onClick={() => openEdit(m)}>编辑</button>
                <button
                  className="danger"
                  onClick={async () => {
                    if (!window.confirm(`删除模型「${m.name}」？`)) return
                    try {
                      await deleteAIModel(accessToken, m.id)
                      setMessage('已删除')
                      await load()
                    } catch (e) {
                      setError(e instanceof Error ? e.message : '删除失败')
                    }
                  }}
                >
                  删除
                </button>
              </div>
            </article>
          ))}
        </div>
        {!loading && items.length === 0 && <p className="subtle">暂无模型，请点击「添加模型」。</p>}
      </section>

      {showModal && (
        // 不在遮罩上绑定点击关闭：避免误触空白处、下拉框收起、触控漂移导致表单被关掉。
        <div className="modal-mask" role="presentation">
          <div
            className="modal-card"
            role="dialog"
            aria-modal="true"
            aria-labelledby="ai-model-modal-title"
            style={{ maxWidth: 520 }}
          >
            <div className="modal-card-header">
              <h3 id="ai-model-modal-title">{editing ? '编辑模型' : '添加模型'}</h3>
              <button
                type="button"
                className="modal-close-btn"
                aria-label="关闭"
                onClick={() => setShowModal(false)}
              >
                ×
              </button>
            </div>
            <label>
              显示名称
              <input value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} />
            </label>
            {!editing && (
              <label>
                类型
                <select
                  value={form.model_type}
                  onChange={(e) => setForm((f) => ({ ...f, model_type: e.target.value as AIModelType }))}
                >
                  {MODEL_TYPES.map((t) => (
                    <option key={t.value} value={t.value}>
                      {t.label}
                    </option>
                  ))}
                </select>
              </label>
            )}
            <label>
              API 地址（须为完整 URL）
              <input
                value={form.api_base_url}
                onChange={(e) => setForm((f) => ({ ...f, api_base_url: e.target.value }))}
              />
              <span className="subtle" style={{ fontSize: 12, marginTop: 4 }}>
                问答：<code>/v1/chat/completions</code> · 嵌入：<code>/v1/embeddings</code> ·
                重排：常见 <code>/v1/rerank</code>（请求体含 model、query、documents、top_n）
              </span>
            </label>
            <label>
              模型 ID（请求体 model 字段）
              <input value={form.model_id} onChange={(e) => setForm((f) => ({ ...f, model_id: e.target.value }))} />
            </label>
            <label>
              API Key{editing && '（留空表示不修改；测试连接可使用已存密钥）'}
              <input
                type="password"
                autoComplete="off"
                value={form.api_key}
                onChange={(e) => setForm((f) => ({ ...f, api_key: e.target.value }))}
              />
            </label>
            {testHint && (
              <div className={testHint.ok ? 'alert success' : 'alert error'} style={{ marginTop: 8 }}>
                {testHint.text}
              </div>
            )}
            <p className="subtle" style={{ fontSize: 12, margin: 0 }}>
              点击背景不会关闭；请用「取消」或右上角 ×，避免误触丢失已填内容。
            </p>
            <div className="action-row">
              <button type="button" onClick={() => setShowModal(false)}>
                取消
              </button>
              <button type="button" disabled={testBusy || !canTestConnection} onClick={() => void runTestConnection()}>
                {testBusy ? '测试中…' : '测试连接'}
              </button>
              <button
                className="primary"
                disabled={loading || !form.name || !form.api_base_url || !form.model_id || (!editing && !form.api_key)}
                onClick={() => void submitModal()}
              >
                保存
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
